name: Test, Lint and Build Image
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/run-lint.yaml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/run-test.yaml
    secrets: inherit

  build:
    name: build & push image
    with:
      tag: ${{ inputs.tag || github.sha || github.ref_name}}
    needs:
      - lint
      - test
    uses: ./.github/workflows/build-image.yaml
    secrets: inherit
