name: Lint
on:
  workflow_call:
    secrets:
      TELEGRAM_CHANNEL:
        required: true
      TELEGRAM_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up GO
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go mod download
      - name: Linting
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout 5m
      - name: Send telegram message after linting failed
        if: failure()
        uses: SOTBI-LLC/gh-actions/actions/notify-telegram@main
        with:
          chat_id: ${{ secrets.TELEGRAM_CHANNEL }}
          bot_token: ${{ secrets.TELEGRAM_TOKEN }}
          text: |
            🔍PR #${{github.event.number}}:
            ❗️Linting failed❗️
            👷: ${{ github.triggering_actor }}
            👀 changes: https://github.com/${{ github.repository }}/pull/${{github.event.number}}
