name: Test
on:
  workflow_call:
    secrets:
      TELEGRAM_CHANNEL:
        required: true
      TELEGRAM_TOKEN:
        required: true
env:
  POSTGRES_URL: "postgresql://energy:postgres@localhost:5432/energy_test?sslmode=disable"

permissions:
  contents: read

jobs:
  testing:
    timeout-minutes: 30
    runs-on: arc-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup GO
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go mod download
      - name: Testing
        run: make test-ci
      - name: Upload Go test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Go-test-results
          path: test-results.json
      - name: Send telegram message after testing failed
        if: failure()
        uses: SOTBI-LLC/gh-actions/actions/notify-telegram@main
        with:
          chat_id: ${{ secrets.TELEGRAM_CHANNEL }}
          bot_token: ${{ secrets.TELEGRAM_TOKEN }}
          text: |
            🔍PR #${{github.event.number}}:
            ❗️Testing failed❗️
            👷: ${{ github.triggering_actor }}
            👀 changes: https://github.com/${{ github.repository }}/pull/${{github.event.number}}
