name: Move jira issue to ...

on:
  workflow_call:
    inputs:
      issue_key:
        description: 'Jira issue key'
        type: string
      transition_name:
        description: 'Jira transition name'
        type: string
        default: HOT to develop


jobs:
  move-jira-issue:
    name: Move jira issue to ${{ inputs.transition_name }}
    runs-on: sotbi-runners
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Move jira issue to ${{ inputs.transition_name }}
        uses: SOTBI-LLC/gh-actions/actions/jira-transition@main
        with:
          transition_name: ${{ inputs.transition_name }}
          issue_key: ${{ inputs.issue_key }}
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
