name: notify

on:
  workflow_call:
    inputs:
      text:
        type: string
        description: Message text
        default: 'Hello, world!'
    secrets:
      TELEGRAM_CHANNEL:
        required: true
      TELEGRAM_TOKEN:
        required: true

jobs:
  send-tg:
    name: Send telegram message
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Send telegram message
        uses: SOTBI-LLC/gh-actions/actions/notify-telegram@main
        with:
          chat_id: ${{ secrets.TELEGRAM_CHANNEL }}
          bot_token: ${{ secrets.TELEGRAM_TOKEN }}
          text: ${{ inputs.text }}
