name: Remove Dynamic
on:
  workflow_call:
    inputs:
      ns:
        type: string
        description: 'Namespace to remove'
        required: true
    secrets:
      KUBE_CONFIG_DATA:
        required: true
      TELEGRAM_CHANNEL:
        required: true
      TELEGRAM_TOKEN:
        required: true

permissions:
  contents: read
jobs:
  cleanup:
    runs-on: sotbi-runners
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
      - name: Show merged branch name
        run: |
          echo "Merged branch: ${{ github.event.pull_request.head.ref }}"
      - name: Branch to lowercase
        id: branch-to-lowercase
        run: echo "branch=$(echo '${{ github.event.inputs.ns || github.event.pull_request.head.ref }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Post-deployment cleanup (delete branch namespaces)
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config
          chmod go-r ~/.kube/config
          kubectl delete namespace ${{ steps.branch-to-lowercase.outputs.branch }} --ignore-not-found=true
  send-tg-success:
    name: Send telegram message
    needs:
     - cleanup
    uses: SOTBI-LLC/gh-actions/.github/workflows/notify.yaml@main
    secrets: inherit
    with:
      text: |
        ${{ github.actor }} removed FRONT from URL: http://${{ steps.branch-to-lowercase.outputs.branch }}.svc.ourzoo.ru
        Removed namespace: ${{ steps.branch-to-lowercase.outputs.branch }}
        View job logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
